database:
  driver: "postgres"
  dbname: "data/database"
  username: "user"
  password: "password"
  host: "localhost"
  port: "5432"
  max_lifetime: 7200
  max_open_conns: 150
  max_idle_conns: 50

server:
  port: "80"
  secret: "TBD"
  #release | debug
  mode: "debug"